Adding an option to provide flow container resource requests from flow parameter
azkaban/azkaban pull request #2780
Opened 2021-03-02 00:35 UTC by jakhani

If cpu and memory requested for a flow container is higher than limit defined in system properties then flow pod will not launch.

Flow parameter introduced for cpu and memory are:
flow.container.cpu.request
flow.container.memory.request

2021-03-02 08:00 UTC, djaiswal83 requested changes
How does it prevent pod from launching if the user provided info is higher than the limit?

2021-03-02 09:45 UTC, abhisheknath2011 commented on azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
> +   * Use CPU request set in flow parameter b) Use CPU request set in system properties c) Use
I believe system properties use case is covered in KubernetesContainerizedImpl constructor. If so, can we update the comment accordingly in both the cpu and memory getter method?

2021-03-02 19:06 UTC, jakhani commented on azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
> +    String flowContainerCPURequest = getFlowContainerCPURequest(flowParam);
Fixed it. Thanks.

2021-03-02 19:06 UTC, jakhani commented on azkaban-common/src/main/java/azkaban/executor/container/KubernetesContainerizedImpl.java
> +   * Use CPU request set in flow parameter b) Use CPU request set in system properties c) Use
Good point. Updated the comment accordingly.

2021-03-02 19:27 UTC, jakhani commented
> How does it prevent pod from launching if the user provided info is higher than the limit?

The pod dispatch will fail. With below mentioned error.
Invalid value: \"8\": must be less than or equal to cpu limit
Invalid value: \"70Gi\": must be less than or equal to memory limit

2021-03-02 19:42 UTC, djaiswal83 approved these changes
Thanks for addressing the comments. The code looks good now.

2021-03-03 00:37 UTC, sshardool commented
> > How does it prevent pod from launching if the user provided info is higher than the limit?
> 
> The pod dispatch will fail. With below mentioned error.
> Invalid value: "8": must be less than or equal to cpu limit
> Invalid value: "70Gi": must be less than or equal to memory limit

Wondering, where is this check implemented ?

2021-03-03 18:56 UTC, merged