Enabled event reporter in a K8s pod to send ready, dispatching, prepa…
azkaban/azkaban pull request #2812
Opened 2021-03-25 21:38 UTC by hqin2016

…ring events, and additional container related data to flow and job life cycle events, continuation to #2802

2021-03-26 23:17 UTC, jakhani submitted a review, later dismissed

2021-03-27 00:20 UTC, djaiswal83 requested changes
Thanks for addressing the comments. I have a couple of minor comments.

2021-03-27 00:20 UTC, djaiswal83 commented on azkaban-common/src/main/java/azkaban/executor/container/PodEventListener.java
> + * It handles event, gets event meta data, and sends meta data to event reporter plugin
nitpick : metadata is a single word.

2021-03-28 18:55 UTC, djaiswal83 approved these changes
Thanks for addressing the comments. Looks good to me.

2021-03-31 16:08 UTC, merged