Use log4j.xml as default log4j configuration file and make sample web…
azkaban/azkaban pull request #3122
Opened 2022-06-30 22:06 UTC by byjiang1996

…server&execserver configs runable

Test:
Can run azkaban-web-server, azkaban-exec-server and azkaban-solo-server successfully with correct log lines.

2022-07-01 00:33 UTC, djaiswal83 requested changes
Thanks for making the change. I have few comments.

2022-07-01 00:33 UTC, djaiswal83 commented on azkaban-exec-server/src/main/bash/internal/internal-start-executor.sh
> +  echo "Exit with error: neither $conf/log4j.xml or $conf/log4j.properties exist."
nor

2022-07-01 00:33 UTC, djaiswal83 commented on azkaban-web-server/src/main/bash/internal/internal-start-web.sh
> +  echo "Exit with error: neither $conf/log4j.xml or $conf/log4j.properties exist."
nor

2022-07-01 00:33 UTC, djaiswal83 commented on azkaban-exec-server/src/main/resources/conf/azkaban.properties
> +mysql.database=az_test
Why do we need this change?

2022-07-11 17:47 UTC, byjiang1996 commented on azkaban-exec-server/src/main/resources/conf/azkaban.properties
> +mysql.database=az_test
The changes here are aborted.

2022-07-11 17:52 UTC, byjiang1996 commented on azkaban-exec-server/src/main/bash/internal/internal-start-executor.sh
> -  echo "Exit with error: neither $conf/log4j.xml or $conf/log4j.properties exist."
Done... Sorry about that

2022-07-11 17:53 UTC, djaiswal83 approved these changes
Looks good to me.

2022-07-11 21:19 UTC, hqin2016 approved these changes
LGTM

2022-07-11 21:20 UTC, merged