Changes neccesary to remove ENUM and move from k8s library 15.0.0 to …
azkaban/azkaban pull request #3128
Opened 2022-07-20 23:27 UTC by amielkelinkedin

The restartPolicy when derived via the ENUM supplied in io.kubernetes:client-java:15.0.0 and io.kubernetes:client-java-api-fluent:15.0.0 is `restartPolicy: NEVER` when it needs to be `restartPolicy: Never`. ENUMs were taken out for the patch in 15.0.1.

2022-07-27 20:24 UTC, byjiang1996 requested changes
LGTM. Thanks for adding the change!

2022-08-01 18:01 UTC, utk-12 approved these changes

2022-08-02 19:08 UTC, amielkelinkedin commented on azkaban-common/src/main/java/azkaban/container/models/AzKubernetesV1SpecBuilder.java
> -import io.kubernetes.client.openapi.models.V1Container.ImagePullPolicyEnum;
@utk-12, the library removed the enums.  The link to the change log is at the top - the bug that was fixed is not included in the changelog, but essentially https://github.com/kubernetes-client/java/issues/2192. There are tests that are affected, but this change accounts for those tests.  Thus the change to the yaml files. Thank you so much!

2022-08-02 19:09 UTC, byjiang1996 approved these changes
LGTM

2022-08-02 19:10 UTC, merged